db_path: path/to/db

# Caminho de origem e destino dos arquivos dos arquivos, o primeiro item é onde os arquivos serão buscados o segundo é
# onde os arquivos convertidos serão salvos.
# É importante observar a sintaxe do yml, os destino deve ter um espaço do porto e virgula, como no exemplo abaixo.
directories:
  /Users/andre/Public: /Users/andre/Public
#  caminho/de/origin: caminho/de/destino